### PR TITLE
Adding specs for `lib/fibonacci.rb`, `lib/people.rb` and `lib/string.rb`

### LINKED ISSUE #8: Add tests
- [ ] fibonacci lab
- [ ] people lab
- [ ] normalize words challenge

### PR DESCRIPTION
**Pull request by jrhorn424**
Originally from @danman01. Opening a PR, I have not reviewed this code yet.
>Wrapped fibonacci and people in modules, and add classes to wrap methods so testing is easier.
>
>Close #8
>
>Updating find longest word method within `lib/string.rb` to use `Enumerable#max` and also show `#max_by`

### CODE REVIEW

**Comment by jrhorn424** [comment]
@gaand The requested review here is **not** urgent.

**Review by gaand — CHANGES_REQUESTED** [review]
Why is this a pull against master?  Isn't there a chicken/egg problem having modules and classes in here?  Does it require reordering the sequence to start with ruby-objects?

**Comment by danman01** [comment]
This PR does have working code in master that should not be there. My thinking was, eventually only the solution branch will have the working code and specs. However, with this PR as a starting place to discuss the tests, I would show the working code and specs, and when that portion is approved, we can get rid of the working code and just have failing specs in master. Then in the solution branch, we have working code and working specs.

I put in modules / classes to have a structure to easily test. Even though we haven't gotten to that point in the sequence, we could still take advantage of the modules / classes to organize our objects, like how we used `module.exports` and `require` statements in JS before diving too deep into those. Or, [after reading about how to test procedural code](http://stackoverflow.com/questions/33642778/rspec-dealing-with-variables-outside-of-methods-classes), we could just verify the outputs of the script are what we expect, and not rely on testing methods of a class.

**Comment by gaand** [comment]
@danman01 If you want to refactor the code into two branches, I'm happy to look it over, but I think the chicken/egg problem needs to be carefully thought through.

@jrhorn424 ☝️

**Comment by danman01** [comment]
See updated PRs with this code split out: https://github.com/ga-wdi-boston/ruby-array-methods/pull/20 and https://github.com/ga-wdi-boston/ruby-array-methods/pull/21

**Pull request closed without merging**
